language: python

python:
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install --user .
  - pip install tox

script:
  - pip list --format=columns | grep container-service-extension
  - python -c 'import pkg_resources; print(pkg_resources.require("container_service_extension")[0].version)'
  - tox -e flake8
