rabbitmq:
    host: rmq.vmware.com
    port: 5672
    user: 'guest'
    password: 'guest'
    exchange: vcdext
    routing_key: cse

vcd:
    host: vcd.vmware.com
    port: 443
    username: 'administrator'
    password: 'enter_your_password'
    api_version: '5.6'
    verify: False
    log: True

service:
    listeners: 2
    logging_level: 20
    logging_format: '%(levelname) -8s %(asctime)s %(name) -8s %(funcName) -8s %(lineno) -5d: %(message)s'
    key_filename: 'id_rsa_cse'
    key_filename_pub: 'id_rsa_cse.pub'
    catalog: 'cse-catalog'
    template_master: 'kubernetes.ova'
    template_node: 'kubernetes.ova'
